### PR TITLE
fixes #13

### LINKED ISSUE #13: Error while building
I get this : 

```

/home/elon/Nimbus/src/Hacks/lagcomp.cpp: In function ‘void LagComp::CreateMove(CUserCmd*)’:
/home/elon/Nimbus/src/Hacks/lagcomp.cpp:62:13: error: conflicting declaration ‘const auto weapon’
   62 |  const auto weapon = (C_BaseCombatWeapon *)entityList->GetClientEntityFromHandle(localplayer->GetActiveWeapon());
      |             ^~~~~~

```

### PR DESCRIPTION
**Pull request by tzekid**

### CODE REVIEW

**Comment by olaulau** [comment]
works for me too

**Comment by acuifex** [comment]
https://github.com/Zedespook/Nimbus/commit/30f14d4bcd00c6d9e83970e21fe290d955be38e4
it's already done.

**Comment by olaulau** [comment]
> [30f14d4](https://github.com/Zedespook/Nimbus/commit/30f14d4bcd00c6d9e83970e21fe290d955be38e4)
> it's already done.

it's the opposite, no ?
zesespook remove the line, whereas tezkid adds it.

**Comment by acuifex** [comment]
no. he does the same thing but makes this with "auto" keyword for some reason.

**Comment by tzekid** [comment]
@acuifex Oh right, my bad :)

**Comment by olaulau** [comment]
I didn't dig into code precisely, but from user point of view :
zedespook's project doesn't compile, but tezkid's one compiles and works.
so for me, the fix is really ok.

**Comment by acuifex** [comment]
@olaulau just use dev... i asked @Zedespook to push fix to master but for some reason he doesn't push.

**Comment by Zedespook** [comment]
I asKED @zEDEsPoOk tO PuSh fix To maSter But fOR SOme rEASOn he doesN'T pusH.

**Comment by Zedespook** [comment]
I pressed wrong button, oopsn

**Pull request closed without merging**
